version: "3.7"
services:
  django:
    build:
      context: django
    ports:
    - 8080:8000
    env_file: .env
  django_db:
    image: mysql:5.7
    env_file: .env
  fastapi:
    build:
      context: fastapi
    ports:
    - 8081:8000
    env_file: .env
  fastapi_db:
    image: mysql:5.7
    env_file: .env
